import { UPGRADE_IDS, type InputMessage, type UpgradeId, type Vector2 } from '@project-maze/shared';
interface StickState extends Vector2 { active: boolean; }
const normalize=(vector:Vector2):Vector2=>{const length=Math.hypot(vector.x,vector.y);if(length<.001)return{x:0,y:0};return{x:vector.x/Math.max(1,length),y:vector.y/Math.max(1,length)}};
export class InputController{
  private readonly keys=new Set<string>();private readonly pointer={x:window.innerWidth/2,y:window.innerHeight/2};private readonly moveStick:StickState={x:0,y:0,active:false};private readonly aimStick:StickState={x:1,y:0,active:false};private readonly getAimOrigin:()=>Vector2;private readonly finePointer=window.matchMedia('(pointer: fine)').matches;private sequence=0;private primaryDown=false;private secondaryDown=false;private autoFire=false;
  constructor(canvas:HTMLCanvasElement,getAimOrigin:()=>Vector2,onUpgrade:(upgrade:UpgradeId)=>void,onAutoFireChanged:(enabled:boolean)=>void){this.getAimOrigin=getAimOrigin;canvas.tabIndex=0;window.addEventListener('keydown',event=>{this.keys.add(event.code);if(!event.repeat&&event.code==='KeyE'){this.autoFire=!this.autoFire;onAutoFireChanged(this.autoFire)}if(!event.repeat&&event.code.startsWith('Digit')){const index=Number(event.code.slice(5))-1;const upgrade=UPGRADE_IDS[index];if(upgrade)onUpgrade(upgrade)}});window.addEventListener('keyup',event=>this.keys.delete(event.code));window.addEventListener('blur',()=>this.resetTransient());window.addEventListener('pointermove',event=>{if(event.pointerType!=='mouse'&&event.pointerType!=='pen')return;this.pointer.x=event.clientX;this.pointer.y=event.clientY});canvas.addEventListener('pointerdown',event=>{canvas.focus({preventScroll:true});if(event.pointerType==='mouse'||event.pointerType==='pen'){if(event.button===0)this.primaryDown=true;if(event.button===2)this.secondaryDown=true}});window.addEventListener('pointerup',event=>{if(event.button===0)this.primaryDown=false;if(event.button===2)this.secondaryDown=false});canvas.addEventListener('contextmenu',event=>event.preventDefault());canvas.addEventListener('wheel',event=>event.preventDefault(),{passive:false});this.bindStick('move-stick',this.moveStick,false);this.bindStick('aim-stick',this.aimStick,true);const secondaryButton=document.querySelector<HTMLElement>('#secondary-action');secondaryButton?.addEventListener('pointerdown',event=>{event.preventDefault();this.secondaryDown=true;secondaryButton.setPointerCapture(event.pointerId)});const releaseSecondary=():void=>{this.secondaryDown=false};secondaryButton?.addEventListener('pointerup',releaseSecondary);secondaryButton?.addEventListener('pointercancel',releaseSecondary)}
  nextMessage():InputMessage{return{type:'input',sequence:++this.sequence,move:this.getMovement(),aim:this.getAim(),primary:this.isPrimary,secondary:this.isSecondary}}
  getMovement():Vector2{if(this.moveStick.active)return{x:this.moveStick.x,y:this.moveStick.y};let x=0,y=0;if(this.keys.has('KeyA')||this.keys.has('ArrowLeft'))x-=1;if(this.keys.has('KeyD')||this.keys.has('ArrowRight'))x+=1;if(this.keys.has('KeyW')||this.keys.has('ArrowUp'))y-=1;if(this.keys.has('KeyS')||this.keys.has('ArrowDown'))y+=1;return normalize({x,y})}
  getAim():Vector2{if(this.aimStick.active)return normalize(this.aimStick);const origin=this.getAimOrigin();return normalize({x:this.pointer.x-origin.x,y:this.pointer.y-origin.y})}
  getPointerPosition():Vector2{if(!this.aimStick.active)return{...this.pointer};const origin=this.getAimOrigin();return{x:origin.x+this.aimStick.x*150,y:origin.y+this.aimStick.y*150}}
  get isPrimary():boolean{return this.primaryDown||this.aimStick.active||this.autoFire}get isSecondary():boolean{return this.secondaryDown}get showCrosshair():boolean{return this.finePointer&&!this.aimStick.active}
  toggleAutoFire():boolean{this.autoFire=!this.autoFire;return this.autoFire}resetTransient():void{this.keys.clear();this.primaryDown=false;this.secondaryDown=false}
  private bindStick(id:string,state:StickState,fires:boolean):void{const area=document.querySelector<HTMLElement>(`#${id}`);const knob=area?.querySelector<HTMLElement>('.stick-knob');if(!area||!knob)return;let pointerId:number|null=null;const maxDistance=44,deadzone=fires?.08:.14;const update=(event:PointerEvent):void=>{const rect=area.getBoundingClientRect();const dx=event.clientX-(rect.left+rect.width/2),dy=event.clientY-(rect.top+rect.height/2),rawLength=Math.hypot(dx,dy),limited=Math.min(maxDistance,rawLength),direction=rawLength<.001?{x:0,y:0}:{x:dx/rawLength,y:dy/rawLength},normalizedLength=limited/maxDistance,adjusted=normalizedLength<=deadzone?0:Math.pow((normalizedLength-deadzone)/(1-deadzone),1.06);state.x=direction.x*adjusted;state.y=direction.y*adjusted;state.active=fires?normalizedLength>deadzone:adjusted>0;knob.style.transform=`translate3d(${direction.x*limited}px, ${direction.y*limited}px, 0)`};area.addEventListener('pointerdown',event=>{event.preventDefault();pointerId=event.pointerId;area.setPointerCapture(pointerId);update(event)});area.addEventListener('pointermove',event=>{if(event.pointerId===pointerId)update(event)});const release=(event:PointerEvent):void=>{if(event.pointerId!==pointerId)return;pointerId=null;state.x=fires?1:0;state.y=0;state.active=false;knob.style.transform=''};area.addEventListener('pointerup',release);area.addEventListener('pointercancel',release)}
}
