import { GAME, type ChooseClassMessage, type JoinMessage, type PlayerClass, type PlayerSnapshot, type RespawnMessage, type ServerMessage, type ThemeId, type UpgradeId, type UpgradeMessage, type WorldSnapshot } from '@project-maze/shared';
import { GameAudio } from './audio';import { InputController } from './input';import { GameRenderer } from './renderer';import { GameUI, type JoinOptions } from './ui';import './style.css';
let socket:WebSocket|null=null;let joinOptions:JoinOptions|null=null;let reconnectTimer:number|null=null;let reconnectDelay=1200;let joined=false;let input:InputController|null=null;let previousSelf:PlayerSnapshot|null=null;let previousProjectileIds=new Set<string>();let lastLevel=1;
const audio=new GameAudio();const renderer=new GameRenderer();function send(message:object):void{if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify(message))}
const ui=new GameUI(options=>{audio.unlock();joinOptions=options;renderer.setTheme(options.theme);ui.enterGame();connect()},(upgrade:UpgradeId)=>{const message:UpgradeMessage={type:'upgrade',upgrade};send(message)},()=>input?.toggleAutoFire()??false,(playerClass:PlayerClass)=>{const message:ChooseClassMessage={type:'chooseClass',playerClass};send(message)},()=>{const message:RespawnMessage={type:'respawn'};send(message)});
await renderer.init(ui.root);input=new InputController(renderer.app.canvas,()=>renderer.getAimOrigin(),upgrade=>send({type:'upgrade',upgrade} satisfies UpgradeMessage),enabled=>ui.setAutoFire(enabled));renderer.app.ticker.add(()=>{if(!input)return;renderer.setInput(input.getPointerPosition(),input.isPrimary,input.isSecondary,joined&&input.showCrosshair)});
function endpoint():string{const configured=import.meta.env.VITE_WS_URL as string|undefined;if(configured)return configured;const protocol=window.location.protocol==='https:'?'wss':'ws';return`${protocol}://${window.location.hostname}:2567`}
function connect():void{if(!joinOptions||socket?.readyState===WebSocket.OPEN||socket?.readyState===WebSocket.CONNECTING)return;if(reconnectTimer!==null){window.clearTimeout(reconnectTimer);reconnectTimer=null}ui.setConnection('connecting');joined=false;const currentSocket=new WebSocket(endpoint());socket=currentSocket;currentSocket.addEventListener('open',()=>{reconnectDelay=1200;const message:JoinMessage={type:'join',name:joinOptions?.name??'Player'};currentSocket.send(JSON.stringify(message))});currentSocket.addEventListener('message',event=>{try{handleServerMessage(JSON.parse(String(event.data))as ServerMessage)}catch(error){console.error('Invalid server message',error);ui.toast('Netzwerkfehler','Der Server hat ungültige Daten gesendet.','danger')}});currentSocket.addEventListener('close',()=>{joined=false;previousSelf=null;previousProjectileIds.clear();input?.resetTransient();ui.setConnection('offline','VERBINDUNG VERLOREN');if(socket===currentSocket&&joinOptions){reconnectTimer=window.setTimeout(connect,reconnectDelay);reconnectDelay=Math.min(8000,Math.round(reconnectDelay*1.65))}});currentSocket.addEventListener('error',()=>ui.setConnection('offline','SERVER NICHT ERREICHBAR'))}
function handleServerMessage(message:ServerMessage):void{if(message.type==='welcome'){joined=true;previousSelf=null;previousProjectileIds.clear();lastLevel=1;ui.setConnection('online','MAZE ALPHA');ui.toast('Arena betreten','Farme Formen und entwickle deinen Tank.','success');return}if(message.type==='error'){ui.toast('Beitritt fehlgeschlagen',message.message,'danger');return}if(message.type==='pong'){ui.setPing(performance.now()-message.sentAt);return}updateWorld(message)}
function updateWorld(snapshot:WorldSnapshot):void{const self=snapshot.players.find(player=>player.id===snapshot.selfId)??null;if(self)playSnapshotAudio(snapshot,self);renderer.setSnapshot(snapshot);const updatedSelf=ui.update(snapshot);if(!updatedSelf)return;if(updatedSelf.dead)input?.resetTransient();if(updatedSelf.level>lastLevel)ui.toast(`Level ${updatedSelf.level}`,'Du hast einen neuen Upgrade-Punkt erhalten.','success');lastLevel=updatedSelf.level;previousSelf={...updatedSelf,position:{...updatedSelf.position},velocity:{...updatedSelf.velocity},upgrades:{...updatedSelf.upgrades}};previousProjectileIds=new Set(snapshot.projectiles.map(projectile=>projectile.id))}
const CLASS_WITH_BULLETS=new Set<PlayerClass>(['core','rapid','sniper','rammer','twin','railgun','crusher','storm','lancer','juggernaut']);function playSnapshotAudio(snapshot:WorldSnapshot,self:PlayerSnapshot):void{if(previousSelf){if(self.health<previousSelf.health-.01&&self.deaths===previousSelf.deaths)audio.damage();if(self.kills>previousSelf.kills)audio.kill();if(self.deaths>previousSelf.deaths)audio.death();if(self.level>previousSelf.level)audio.level()}if(CLASS_WITH_BULLETS.has(self.playerClass)){const fired=snapshot.projectiles.some(projectile=>projectile.ownerId===self.id&&!previousProjectileIds.has(projectile.id));if(fired)audio.shot(self.playerClass)}}
window.setInterval(()=>{if(joined&&input&&socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify(input.nextMessage()))},1000/GAME.tickRate);window.setInterval(()=>{if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify({type:'ping',sentAt:performance.now()}))},2000);window.addEventListener('error',event=>{console.error(event.error??event.message);ui.toast('Client-Fehler','Ein Darstellungsfehler wurde abgefangen. Bitte Konsole prüfen.','danger')});window.addEventListener('unhandledrejection',event=>{console.error(event.reason);ui.toast('Client-Fehler','Ein Hintergrundfehler wurde abgefangen.','danger')});
const storedTheme=(window.localStorage.getItem('project-maze-theme')as ThemeId|null)??'midnight';document.documentElement.dataset.theme=storedTheme;const themeSelect=document.querySelector<HTMLSelectElement>('#theme');if(themeSelect){themeSelect.value=storedTheme;themeSelect.addEventListener('change',()=>{const theme=themeSelect.value as ThemeId;window.localStorage.setItem('project-maze-theme',theme);document.documentElement.dataset.theme=theme;renderer.setTheme(theme)})}renderer.setTheme(storedTheme);
