import { Graphics } from 'pixi.js';
import type { Vector2 } from '@project-maze/shared';
interface Particle{position:Vector2;velocity:Vector2;life:number;maxLife:number;radius:number;color:number;drag:number}
export class ParticleField{readonly graphics=new Graphics();private readonly particles:Particle[]=[];
  /** Qualitätsstufe (quality.ts): Faktor auf jede Menge und harte Obergrenze. */
  private scale=1;private cap=360;
  setQuality(scale:number,cap:number):void{this.scale=scale;this.cap=cap;if(this.particles.length>cap)this.particles.splice(0,this.particles.length-cap)}
  /** Mindestens ein Partikel: Ein Treffer ohne jede Rückmeldung wäre schlimmer als ein sparsamer. */
  private menge(count:number):number{return Math.max(1,Math.round(count*this.scale))}
  burst(origin:Vector2,color:number,count=8,power=150,life=.35):void{const total=this.menge(count);for(let index=0;index<total;index+=1){const angle=Math.random()*Math.PI*2,speed=power*(.25+Math.random()*.75);this.particles.push({position:{...origin},velocity:{x:Math.cos(angle)*speed,y:Math.sin(angle)*speed},life:life*(.7+Math.random()*.55),maxLife:life,radius:1.8+Math.random()*3.8,color,drag:4+Math.random()*4})}}muzzle(origin:Vector2,direction:Vector2,color:number):void{const point={x:origin.x+direction.x*48,y:origin.y+direction.y*48};const total=this.menge(4);for(let index=0;index<total;index+=1){const angle=Math.atan2(direction.y,direction.x)+(Math.random()-.5)*.52,speed=90+Math.random()*130;this.particles.push({position:point,velocity:{x:Math.cos(angle)*speed,y:Math.sin(angle)*speed},life:.1+Math.random()*.12,maxLife:.22,radius:1.5+Math.random()*2.5,color,drag:7})}}update(delta:number):void{for(let index=this.particles.length-1;index>=0;index-=1){const particle=this.particles[index];if(!particle)continue;particle.life-=delta;if(particle.life<=0){this.particles.splice(index,1);continue}const damping=Math.exp(-particle.drag*delta);particle.velocity.x*=damping;particle.velocity.y*=damping;particle.position.x+=particle.velocity.x*delta;particle.position.y+=particle.velocity.y*delta}if(this.particles.length>this.cap)this.particles.splice(0,this.particles.length-this.cap)}draw():void{this.graphics.clear();for(const particle of this.particles){const progress=Math.max(0,Math.min(1,particle.life/particle.maxLife));this.graphics.circle(particle.position.x,particle.position.y,particle.radius*(.45+progress*.55)).fill({color:particle.color,alpha:progress*.82})}}}
